#!/bin/bash
# 接收文件示例脚本

echo "=== 接收文件示例 ==="
echo ""
echo "使用方法："
echo "  ./sendme receive <ticket> [选项]"
echo ""
echo "示例："
echo ""
echo "1. 基本用法（保存到当前目录）："
echo "   ./sendme receive <ticket>"
echo ""
echo "2. 保存到指定目录："
echo "   ./sendme receive <ticket> --output ./downloads"
echo ""
echo "3. 保存到指定路径（可重命名）："
echo "   ./sendme receive <ticket> --output ./my_file.pdf"
echo ""
echo "4. 指定端口（同一台机器时使用）："
echo "   ./sendme receive <ticket> --port 9001 --output ./downloads"
echo ""
echo "完整示例："
echo "   ./sendme receive eyJwZWVyX2FkZHIiOiIvaXA0LzEyNy4wLjAuMS90Y3AvOTAwMC9wMnAvUW1OZVhVU3NKbm9hZmNRa1hpZXp6Z0FCM2J5VHN4eEVVcUZoZkxvMlhjVnM4dyIsImZpbGVfaGFzaCI6ImI4ZmFhMjhlMmVjOWJlNmQ4NWMyN2EwNWEyNzkxYTU2MzIxZWY5N2Q3NzJkYTlkZDNlNTBiOTM4YWM4M2RhNzMiLCJmaWxlX25hbWUiOiJkb2N1bWVudC5wZGYiLCJmaWxlX3NpemUiOjI2MjE0NDB9= --output ./downloads"
echo ""
